// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5VjEreNQWrEm9qpDmD3530b453t90P0k',
    appId: '1:189567646506:web:c8b475d3b4fa4a11db7c53',
    messagingSenderId: '189567646506',
    projectId: 'stride-67509',
    authDomain: 'stride-67509.firebaseapp.com',
    storageBucket: 'stride-67509.appspot.com',
    measurementId: 'G-2H9P06B9GG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCeyOmY98YLbC1UidGNulsxNXLwj3Ts1nY',
    appId: '1:189567646506:android:a58a81a01a1bdc9ddb7c53',
    messagingSenderId: '189567646506',
    projectId: 'stride-67509',
    storageBucket: 'stride-67509.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAErNKQdwpDdp58GWh4sgwJ40DHWm5UIhI',
    appId: '1:189567646506:ios:7bea8b668fae01e5db7c53',
    messagingSenderId: '189567646506',
    projectId: 'stride-67509',
    storageBucket: 'stride-67509.appspot.com',
    iosClientId: '189567646506-vohkde93rsmkq8ovgt49dgvcfopodrq1.apps.googleusercontent.com',
    iosBundleId: 'com.example.strideDelivery',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAErNKQdwpDdp58GWh4sgwJ40DHWm5UIhI',
    appId: '1:189567646506:ios:7bea8b668fae01e5db7c53',
    messagingSenderId: '189567646506',
    projectId: 'stride-67509',
    storageBucket: 'stride-67509.appspot.com',
    iosClientId: '189567646506-vohkde93rsmkq8ovgt49dgvcfopodrq1.apps.googleusercontent.com',
    iosBundleId: 'com.example.strideDelivery',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC5VjEreNQWrEm9qpDmD3530b453t90P0k',
    appId: '1:189567646506:web:81c9250b1bfaf3b3db7c53',
    messagingSenderId: '189567646506',
    projectId: 'stride-67509',
    authDomain: 'stride-67509.firebaseapp.com',
    storageBucket: 'stride-67509.appspot.com',
    measurementId: 'G-SPPCB0CND8',
  );
}
